const express = require('express')
const dbConnect = require('./dbConnect/db')
const cors = require('cors')
const env = require('dotenv').config()
const app = express()
const port = process.env.PORT
dbConnect()
app.use(express.json())
app.use(cors())
const userRouter = require('./router/user')
app.use(userRouter)
const adminRouter = require('./router/admin')
app.use(adminRouter)
const salerRouter = require('./router/saler')
app.use(salerRouter)
const viewsRouter = require('./router/views')
app.use(viewsRouter)
const cartRouter = require('./router/cart')
app.use(cartRouter)
const orderRouter = require('./router/order')
app.use(orderRouter)
const productCatRouter = require('./router/productCat')
app.use(productCatRouter)
const brandCatRouter = require('./router/brandCat')
app.use(brandCatRouter)
app.listen(port, () => console.log(`servire is running at port ${port}`))